// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace StoryboardTables
{
	public partial class AllViewCell : UICollectionViewCell
	{
		public AllViewCell (IntPtr handle) : base (handle)
		{
		}

		public UIKit.UILabel Name { get{ return TodoName; } }
	}
}
