// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace StoryboardTables
{
	public partial class AllViewController : UICollectionView
	{
		public AllViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
