// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace StoryboardTables
{
	public partial class PeekViewController : UIViewController
	{
		public PeekViewController (IntPtr handle) : base (handle)
		{
		}
		[Export ("initWithCoder:")]
		public PeekViewController (NSCoder coder) : base (coder)
		{
		}

		Task current {get;set;}

		// this will be called before the view is displayed 
		public void SetTodo (Task todo) {
			current = todo;
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			View.BackgroundColor = UIColor.White;

			Name.Text = current.Name;
			Notes.Text = current.Notes;
			if (current.Done)
				Done.Image = UIImage.FromBundle ("checkbox");
			else
				Done.Image = UIImage.FromBundle ("box");
			
		}

		public override IUIPreviewActionItem[] PreviewActionItems {
			get {
				return PreviewActions;
			}
		}
		IUIPreviewActionItem[] PreviewActions {
			get {
				var action1 = PreviewActionForTitle ("View");
				var action2 = PreviewActionForTitle ("Delete", UIPreviewActionStyle.Destructive);

				return new IUIPreviewActionItem [] { action1, action2};
			}
		}
		static UIPreviewAction PreviewActionForTitle (string title, UIPreviewActionStyle style = UIPreviewActionStyle.Default)
		{
			return UIPreviewAction.Create (title, style, (action, previewViewController) => {
				var peekViewController  = (PeekViewController)previewViewController;
				if (style == UIPreviewActionStyle.Destructive) {
					// delete
					Console.WriteLine ("#### Delete PA {0} ", action.Title);
				} else {
					//view
					Console.WriteLine ("---- View PA {0} ", action.Title);
				}
					

			});
		}
	}
}
